---
driver:
  name: docker
platforms:
  - name: debian-12
    image: debian:12
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    capabilities:
      - SYS_ADMIN
    command: /lib/systemd/systemd
  - name: ubuntu-2404
    image: ubuntu:24.04
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    capabilities:
      - SYS_ADMIN
    command: /lib/systemd/systemd
  - name: rockylinux-9
    image: rockylinux:9
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    capabilities:
      - SYS_ADMIN
    command: /usr/sbin/init
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        common_upgrade_dist: false
        common_upgrade_packages: false
verifier:
  name: ansible
